### ISSUE TITLE
Bonjour je n'arrive pas à l'installer sur mon raspberry pi 3

### ISSUE THREAD

**Issue by Jean-Bernard-Hallez** [jeroendoggen/youtube-to-mpd#10]
Je télécharge https://pypi.python.org/pypi/youtube_to_mpd/
je le place et le décompresse avec:
tar xzf youtube_to_mpd-0.2.tar.gz

puis j'essaye de l'installer:
python setup.py

il me dit:
Traceback (most recent call last):
  File "setup.py", line 10, in <module>
    from youtube_to_mpd import __version__
ImportError: cannot import name __version__

Que faire ??? Merci....

**Comment by Jean-Bernard-Hallez** [comment]
Pour une installation : 
pip install youtube-to-mpd
il me dit:
Collecting youtube-to-mpd
  Using cached youtube_to_mpd-0.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-4cVqQS/youtube-to-mpd/setup.py", line 13, in <module>
        with open('README.rst') as readme_file:
    IOError: [Errno 2] No such file or directory: 'README.rst'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-4cVqQS/youtube-to-mpd/

**Comment by Cocosushi6** [comment]
Bonjour,
Le mieux est d'essayer avec `git clone https://github.com/jeroendoggen/youtube-to-mpd` (assurez-vous d'avoir `git` d'installé avant). Vous pouvez ensuite essayer `cd src/ && sudo python setup.py install`, ce qui, normalement, devrait installer le module. 
Par contre, c'est un module en alpha, donc je pense qu'il n'est pas complètement fonctionnel, voire complètement impossible à faire fonctionner.

Je pense que le mainteneur ne comprend pas le français, le mieux sur Github et en général est d'ouvrir une issue en anglais :)
